name: Release

# This workflow is triggered manually from the GitHub website.
# To run it, click the "Actions" tab on the repo page.
on:
  workflow_dispatch:
    inputs:
      model_name:
        required: true
        description: The name of the Replicate model to publish, in the format `username-or-org/modelname`.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
          tool-cache: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Cog and NVIDIA drivers
        run: |
          curl https://replicate.github.io/codespaces/scripts/install-cog.sh | bash
          
      - name: Install Cog v0.8.0-beta3
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/v0.8.0-beta3/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          
      - name: Print Docker and Cog version info
        run: |
          docker version
          cog --version

      - name: Download weights
        run: |
          cog run script/download-weights
  
      - name: Log in to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin

      - name: Push to Replicate
        run: |
          cog push r8.im/${{ inputs.model_name }}